[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "https://deploy-preview-42--musical-lokum-8fe231.netlify.app/"
  to = "https://deploy-preview-42--musical-lokum-8fe231.netlify.app/"
  status = 200


[build]
  command = "npm run build"
  publish = ".next"